"""AI agent layer: Gemini with real tools over the live database and solver.

The model can answer questions, run read-only SQL, view any timetable,
edit university data (coordinator only) and trigger the CP-SAT solver.
Stateless per request: the frontend sends the conversation history.
"""

from __future__ import annotations

import json
import os
from typing import Any

import requests as http

from . import db
from .solver import solve_timetable

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")
API_URL = "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={key}"

DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
PERIODS = ["8:15-9:05", "9:05-9:55", "10:10-11:00", "11:00-11:50",
           "11:50-12:40", "1:40-2:30", "2:30-3:20", "3:20-4:05"]

SYSTEM_PROMPT = """You are Roomline, the AI assistant inside a University Room Scheduler used by the \
Department of Computer Science (ACSE). You help faculty viewers and the Timetable Coordinator.

Facts about the system:
- 8 periods/day, Monday-Saturday, times: %s.
- Each of 34 sections has exactly one free day; practicals are 2 consecutive periods and only in Lab rooms.
- The schedule is generated by a CP-SAT constraint solver; if it exists, it has ZERO hard-constraint violations.
- Tables: users(id,email,full_name,role), faculty(id,name,max_per_day), rooms(id,name,capacity,type 'Lab'/'Class'), \
sections(id,name,students), subjects(id,code,name), section_subjects(section_id,subject_id,faculty_id,lecture_hours,practical_hours), \
schedules(id,status,sessions JSON,stats JSON,created_at), room_requests(id,user_id,section_id,preferred_room,reason,letter_path,status,decided_by,decided_at,created_at).
- sessions JSON is a list of {day, slot, duration, sectionId, courseId, roomId, facultyId}. courseId ends in '-practical' or '-lecture'.

Rules:
- Faculty viewers may only ask questions and view timetables; data edits, solving and approving are coordinator-only. \
Refuse politely if a viewer asks for those.
- Before ANY edit (update_data) or solve (solve_schedule), state plainly what you are about to do and why. \
After an edit, offer to regenerate the schedule — a solve is needed for changes to appear in the timetable.
- Use run_query for counts, listings and lookups. Use view_timetable when asked about someone's actual weekly schedule.
- If asked why no schedule exists or data looks odd, investigate with run_query and explain concretely.
- Be concise and factual; you are an operations assistant, not a chatbot. Use the department's data, never invent entries.""" % ", ".join(PERIODS)

TOOLS = [{
    "function_declarations": [
        {"name": "get_overview", "description": "Counts of faculty/rooms/sections/subjects, current schedule status and stats, pending room requests.",
         "parameters": None},
        {"name": "run_query", "description": "Run a read-only SQLite SELECT query against the app database and return rows as JSON.",
         "parameters": {"type": "OBJECT", "properties": {"sql": {"type": "STRING", "description": "A single SELECT statement"}}, "required": ["sql"]}},
        {"name": "view_timetable", "description": "Get the scheduled sessions for one section, room or faculty member from the active schedule.",
         "parameters": {"type": "OBJECT", "properties": {
             "view": {"type": "STRING", "enum": ["section", "room", "faculty"]},
             "entity_name": {"type": "STRING", "description": "Name or id of the section, room or faculty member"}},
             "required": ["view", "entity_name"]}},
        {"name": "solve_schedule", "description": "Regenerate the whole timetable with the CP-SAT solver. Takes about 10-60 seconds. Coordinator only.",
         "parameters": None},
        {"name": "update_data", "description": "Insert or update one row of university data. Coordinator only. Call get_overview/run_query first to confirm values; describe the change to the user before calling.",
         "parameters": {"type": "OBJECT", "properties": {
             "table": {"type": "STRING", "enum": ["faculty", "rooms", "sections", "subjects", "section_subjects"]},
             "row_json": {"type": "STRING", "description": "The row as a JSON object with the table's column names; section_subjects needs section_id, subject_id, faculty_id"}},
             "required": ["table", "row_json"]}},
    ]
}]


def _overview() -> list[dict]:
    uni = db.load_university()
    sched = db.active_schedule()
    pending = db.list_requests()
    pending = [r for r in pending if r["status"] == "pending"]
    return [{
        "faculty": len(uni["faculty"]), "rooms": len(uni["rooms"]),
        "sections": len(uni["sections"]), "subjects": len(uni["subjects"]),
        "assignments": len(uni["section_subjects"]),
        "active_schedule": {"generated_at": sched["createdAt"], "stats": sched["stats"]} if sched else None,
        "pending_room_requests": len(pending),
    }]


def _entity_id(view: str, name: str, uni: dict) -> str | None:
    table = {"section": "sections", "room": "rooms", "faculty": "faculty"}[view]
    rows = uni[table]
    name_l = name.strip().lower()
    for r in rows:
        if r["id"] == name or r["name"].lower() == name_l:
            return r["id"]
    for r in rows:
        if name_l in r["name"].lower():
            return r["id"]
    return None


def _view_timetable(view: str, entity_name: str) -> list[dict]:
    sched = db.active_schedule()
    if not sched:
        return [{"note": "No active schedule yet — the coordinator must generate one first."}]
    uni = db.load_university()
    ent_id = _entity_id(view, entity_name, uni)
    if not ent_id:
        return [{"note": f"No {view} matching {entity_name!r}.", "available": [r["name"] for r in uni[{"section": "sections", "room": "rooms", "faculty": "faculty"}[view]][:40]]}]
    subj_by_id = {s["id"]: s["name"] for s in uni["subjects"]}
    fac_by_id = {f["id"]: f["name"] for f in uni["faculty"]}
    room_by_id = {r["id"]: r["name"] for r in uni["rooms"]}
    sec_by_id = {s["id"]: s["name"] for s in uni["sections"]}
    out = []
    for s in sched["sessions"]:
        if view == "section" and s["sectionId"] != ent_id: continue
        if view == "room" and s["roomId"] != ent_id: continue
        if view == "faculty" and s["facultyId"] != ent_id: continue
        out.append({
            "day": s["day"], "periods": f"{PERIODS[s['slot']]} ({s['duration']}p)",
            "subject": subj_by_id.get(s["courseId"].replace("-practical", "").replace("-lecture", ""), s["courseId"]),
            "kind": "practical" if s["courseId"].endswith("-practical") else "lecture",
            "faculty": fac_by_id.get(s["facultyId"], s["facultyId"]),
            "room": room_by_id.get(s["roomId"], s["roomId"]),
            "section": sec_by_id.get(s["sectionId"], s["sectionId"]),
        })
    out.sort(key=lambda x: (DAYS.index(x["day"]), x["periods"]))
    return out or [{"note": "No sessions for this entity in the active schedule."}]


def _run_query(sql: str) -> Any:
    s = sql.strip().rstrip(";")
    if not s.lower().startswith("select") or any(k in s.lower().split() for k in
            ("insert", "update", "delete", "drop", "alter", "create", "attach", "pragma")):
        return [{"error": "Only single read-only SELECT statements are allowed."}]
    try:
        return db.query(s, ())[:200]
    except Exception as e:
        return [{"error": f"Query failed: {e}"}]


def _dispatch(name: str, args: dict, user: dict) -> Any:
    is_coord = db.get_role(user["id"]) == "coordinator"
    if name == "get_overview":
        return _overview()
    if name == "run_query":
        return _run_query(args.get("sql", ""))
    if name == "view_timetable":
        return _view_timetable(args.get("view", "section"), args.get("entity_name", ""))
    if name == "solve_schedule":
        if not is_coord:
            return [{"error": "Only the Timetable Coordinator can generate schedules."}]
        uni = db.load_university()
        if not uni["sections"] or not uni["section_subjects"]:
            return [{"error": "No teaching data yet."}]
        days, num_slots, sections, rooms, faculty_max, assignments = db.solver_inputs(uni)
        result = solve_timetable(days, num_slots, sections, rooms, faculty_max, assignments)
        if result["status"] != "ok":
            return [{"result": result["status"], "detail": result.get("detail", "")}]
        db.archive_schedules()
        db.insert_schedule(result["sessions"], result["stats"])
        return [{"result": "ok", "stats": result["stats"]}]
    if name == "update_data":
        if not is_coord:
            return [{"error": "Only the Timetable Coordinator can edit data."}]
        table = args.get("table", "")
        try:
            row = json.loads(args.get("row_json", "{}"))
            assert isinstance(row, dict) and row
        except Exception:
            return [{"error": "row_json must be a JSON object of column -> value."}]
        key = "section_id,subject_id" if table == "section_subjects" else "id"
        try:
            db.upsert(table, [row], key=key)
            return [{"ok": True, "table": table, "row": row}]
        except Exception as e:
            return [{"error": f"Update failed: {e}"}]
    return [{"error": f"Unknown tool {name}"}]


def _part_text(part: dict) -> str:
    return part.get("text", "")


def chat(message: str, history: list[dict], user: dict) -> dict:
    """history: [{role: 'user'|'model', text: str}] excluding the new message."""
    if not GEMINI_API_KEY:
        return {"error": "AI assistant is not configured (GEMINI_API_KEY missing)."}
    contents = []
    for h in history[-12:]:
        role = "model" if h.get("role") == "model" else "user"
        contents.append({"role": role, "parts": [{"text": str(h.get("text", ""))[:4000]}]})
    contents.append({"role": "user", "parts": [{"text": message[:6000]}]})

    for _ in range(6):
        resp = http.post(
            API_URL.format(model=GEMINI_MODEL, key=GEMINI_API_KEY),
            json={"system_instruction": {"parts": [{"text": SYSTEM_PROMPT}]},
                  "contents": contents, "tools": TOOLS},
            timeout=120,
        )
        if resp.status_code != 200:
            try:
                detail = resp.json().get("error", {}).get("message", resp.text)
            except Exception:
                detail = resp.text
            if resp.status_code == 429 or "quota" in detail.lower():
                return {"error": "The free Gemini tier is rate-limited (about 5 requests/minute). Wait a few seconds and send that again, or enable billing on the key for higher limits."}
            return {"error": f"AI request failed: {detail}"}
        data = resp.json()
        cand = (data.get("candidates") or [{}])[0]
        parts = ((cand.get("content") or {}).get("parts")) or []
        calls = [p["functionCall"] for p in parts if "functionCall" in p]
        if not calls:
            return {"reply": "\n".join(filter(None, (_part_text(p) for p in parts))).strip() or "(empty reply)"}
        contents.append({"role": "model", "parts": parts})
        outs = []
        for call in calls:
            result = _dispatch(call["name"], call.get("args", {}) or {}, user)
            outs.append({"functionResponse": {
                "name": call["name"],
                "response": {"content": json.dumps(result, default=str)[:8000]},
            }})
        contents.append({"role": "user", "parts": outs})

    return {"error": "The assistant used too many steps for this request — try a smaller question."}
